umd-lib/dspace-angular

- src/index.html
- src/themes/drum/app/header/header.component.html
- src/themes/drum/app/umd-header/umd-header.component.ts
- src/themes/drum/theme.module.ts
~Include the script embed for the UMD header banner in the top-level HTML index template.~
Create a ds-umd-header component that injects the script tag to render the UMD header banner.
https://issues.umd.edu/browse/LIBDRUM-654
> LIBDRUM-654. Add UMD header.

- src/themes/drum/app/umd-header/umd-header.component.ts
Check for an existing #umdheader-main element before inserting the script tag, so we only add the header once.
https://issues.umd.edu/browse/LIBDRUM-654
> LIBDRUM-654. Ensure UMD header only gets added once.

- src/themes/drum/styles/_global-styles.scss
Adjusted the top margin of the "notifications-wrapper" used to present notifications, so that the top edge of notifications are no longer obscured by the UMD campus banner.
https://issues.umd.edu/browse/LIBDRUM-694
> LIBDRUM-694. Push notifications below UMD campus banner

- config/config.yml
Modified the "standardBundles" list in "config/config.yml" to add the PRESERVATION bundle type.
https://issues.umd.edu/browse/LIBDRUM-666
> LIBDRUM-666. Add PRESERVATION to list of standard bundles

- .vscode/launch.json
- README-DRUM.md
Added "Launch Chrome against localhost" launch configuration to enable VS Code to launch Chrome and connect to it to use the debugger.
Added instructions for using the VS Code debugger to the "README-DRUM.md" file.
https://issues.umd.edu/browse/LIBDRUM-700
> LIBDRUM-700. Added config and documentation for using VS Code debugger

- src/app/access-control/epeople-registry/eperson-form/eperson-form.component.html
- src/app/access-control/epeople-registry/eperson-form/eperson-form.component.spec.ts
- src/app/access-control/epeople-registry/eperson-form/eperson-form.component.ts
- src/app/core/core.module.ts
- src/app/core/eperson/ldap-data.service.ts
- src/app/core/eperson/models/eperson.model.ts
- src/app/core/eperson/models/ldap.model.ts
- src/app/core/eperson/models/ldap.resource-type.ts
- src/app/shared/testing/ldap-data-service.stub.ts
- src/assets/i18n/en.json5
On the EPerson edit form, added a "UM Directory Information" section, with information about the EPerson retrieved from LDAP (if the eperson is known to LDAP).
Added an "ldap" link to the EPerson model, and added an LdapDataService to handle retrieving information from the link.
Added a "stub" LdapDataService to the tests, so that the existing EPerson tests would pass.
https://issues.umd.edu/browse/LIBDRUM-660
> LIBDRUM-660. Added "UM Directory Information" section to EPerson form

- src/app/access-control/epeople-registry/eperson-form/eperson-form.component.html
- src/app/access-control/epeople-registry/eperson-form/eperson-form.component.spec.ts
- src/app/core/core.module.ts
- src/app/core/eperson/models/ldap.model.ts
- src/app/core/eperson/models/unit.model.ts
- src/app/core/eperson/models/unit.resource-type.ts
- src/assets/i18n/en.json5
Building on the work done in LIBDRUM-660, modified the "UM Directory Information" section of "Edit EPerson" to display "matched" and "unmatched" Units an EPerson belongs to, based on their LDAP criteria.
The following classes anticipate the "unit" front-end work being done in LIBDRUM-676:
* src/app/core/eperson/unit-data.service.ts
* src/app/core/eperson/models/unit.model.ts
* src/app/core/eperson/models/unit.resource-type.ts
https://issues.umd.edu/browse/LIBDRUM-669
_Add references/links to any related issues or PRs. These may include:_
* Fixes #[issue-number]
* Requires DSpace/DSpace#[pr-number] (if a REST API PR is required to test this)
Short summary of changes (1-2 sentences).
Please add a more detailed description of the changes made by your PR. At a minimum, providing a bulleted …
> LIBDRUM-669. Display matched/unmatched Units based on LDAP criteria

- src/themes/drum/app/community-list-page/community-list-page.component.html
- src/themes/drum/app/community-list-page/community-list-page.component.ts
- src/themes/drum/app/community-list-page/community-list-service.ts
- src/themes/drum/app/community-list-page/community-list/community-list.component.html
- src/themes/drum/app/community-list-page/community-list/community-list.component.spec.ts
- src/themes/drum/app/community-list-page/community-list/community-list.component.ts
- src/themes/drum/app/home-page/home-page.component.html
- src/themes/drum/app/home-page/home-page.component.ts
- src/themes/drum/eager-theme.module.ts
- src/themes/drum/lazy-theme.module.ts
- Display community lists grouped by community groups on the home page.
- Configure the community lists to display only 5 items initially.
- Prevent reload of the home page when the "show more" button is clicked.
https://issues.umd.edu/browse/LIBDRUM-702
> LIBDRUM-702. Home page customization.

- src/app/core/data/base/data-service.decorator.spec.ts
Replaced the timestamp (intended to produce unique "testType" instances) with UUID, because intermittent failures are occurring when tests are running quickly enough that the "new Data().getTime()" function is returning the same timestamp for multiple tests.
https://issues.umd.edu/browse/LIBDRUM-709
> LIBDRUM-709. Fix data-service.decorator.spec.ts intermittent failures

- config/config.yml
- src/themes/drum/app/footer/footer.component.html
Modified the "config/config.yml" file to suppress display of the "End User Agreement".
Also removed the "End User Agreement" link from the footer.
https://issues.umd.edu/browse/LIBDRUM-698
> LIBDRUM-698. Modified config to suppress End User Agreement

- src/themes/drum/app/item-page/json-ld/json-ld-dataset.component.ts
- src/themes/drum/app/item-page/json-ld/json-ld-dataset.transfomer.ts
- src/themes/drum/app/item-page/json-ld/json-ld-dataset.transformer.spec.ts
- src/themes/drum/app/item-page/json-ld/json-ld.service.spec.ts
- src/themes/drum/app/item-page/json-ld/json-ld.service.ts
- src/themes/drum/app/item-page/json-ld/mocks/mock-json-ld-items.ts
- src/themes/drum/app/item-page/simple/item-page.component.html
- src/themes/drum/app/item-page/simple/item-page.component.ts
- src/themes/drum/lazy-theme.module.ts
Created a "JsonLdService" provides JSON-LD scripts for insertion into web pages, based on the items "dc.type". This implementation currently works for items of type "Dataset".
https://issues.umd.edu/browse/LIBDRUM-683
> LIBDRUM-683. Initial implementation of Dataset JSON-LD

- src/app/submission/sections/cc-license/submission-section-cc-licenses.component.html
- src/assets/i18n/en.json5
Added an explanatory note to Creative Commons license step. Editing the
"stock" file, because this component is not in the "src/themes/custom/"
hierarchy, indicating that it is not themeable).
https://umd-dit.atlassian.net/browse/LIBDRUM-727
> LIBDRUM-727. Added explanatory note to Creative Commons license step

- src/app/app-routing-paths.ts
- src/app/app-routing.module.ts
- src/app/core/shared/bitstream.model.ts
- src/app/restricted-access/restricted-access-page-routing.module.ts
- src/app/restricted-access/restricted-access-page.module.ts
- src/app/restricted-access/restricted-access.component.html
- src/app/restricted-access/restricted-access.component.ts
- src/app/shared/bitstream-download-page/bitstream-download-page.component.spec.ts
- src/app/shared/bitstream-download-page/bitstream-download-page.component.ts
- src/app/shared/file-download-link/file-download-link.component.html
- src/app/shared/file-download-link/file-download-link.component.spec.ts
- src/app/shared/file-download-link/file-download-link.component.ts
- src/assets/i18n/en.json5
- src/themes/drum/lazy-theme.module.ts
Added "embargoRestriction" field to "BitstreamModel' (corresponding
to the changes to the "BItstreamRest" model on the back-end, that
contains one of the following strings, based on the embargo status of the
bitstream:
* "NONE" - no embargo (or embargo on item has been lifted)
* "FOREVER" - the embargo never ends
* A date (in yyyy-MM-dd) format, indicating the embargo lift date
Displays a "(RESTRICTED ACCESS)" text marker below the download link
whenever the bitstream has an active embargo (shown for all users, even
if the user can actually download the bitstream).
Added a "restricted-access" module that shows the "Restricted Access"
page when a bitstream is embargoed, or otherwise not downloadable by
the user (such as due to a "Campus" IP restriction, and the user is
off-campus).
The …
> LIBDRUM-678. Added Embargo/Restricted Access handling

- src/assets/i18n/en.json5
- src/themes/drum/app/item-page/simple/item-types/untyped-item/untyped-item.component.html
- src/themes/drum/app/item-page/simple/item-types/untyped-item/untyped-item.component.ts
Modified the "simple item" display as described in the issue.
The dynamic label changes are handled in the “ngOnInit” method
of the “UntypedItemComponent” class, which passes the appropriate
I18n key for the “dc.description.uri” and “dc.identifier.citation” based
on whether the item type is “Dataset” or “Software” or something else.
https://umd-dit.atlassian.net/browse/LIBDRUM-740
> LIBDRUM-740. Reorganize simple item display

- src/app/core/auth/auth.interceptor.ts
- src/assets/i18n/en.json5
Modified the "AuthInterceptor" class to place the "CAS" authentication method as the first entry in the sorted array, instead of "password". This ensures that that the "CAS" option will appear first in the "LoginComponent" drop-down list.
Modified button labels in the "en.json5" file to match the requests in the issue.
https://umd-dit.atlassian.net/browse/LIBDRUM-734
> LIBDRUM-734. Switch order of log in options on Log In menu

- src/app/core/shared/bitstream.model.ts
Fixed an issue where the "(RESTRICTED ACCESS)" marker was being displayed on the submission form for newly uploaded items.
Modified the "isEmbargoed()" method to return false if the "embargoRestriction" field is undefined, which it will be for a newly uploaded file on the submission form.
https://umd-dit.atlassian.net/browse/LIBDRUM-751
_Add references/links to any related issues or PRs. These may include:_
* Fixes #[issue-number]
* Requires DSpace/DSpace#[pr-number] (if a REST API PR is required to test this)
Short summary of changes (1-2 sentences).
Please add a more detailed description of the changes made by your PR. At a minimum, providing a bulleted list of changes in your PR is helpful to reviewers.
List of changes in this PR:
* First, ...
* Second, ...
**Include guidance for how …
> LIBDRUM-751. Limit "RESTRICTED ACCESS" marker display to existing items

- README-DRUM.md
- src/assets/i18n/en.json5
- src/themes/drum/app/footer/footer.component.html
- src/themes/drum/app/footer/footer.component.scss
- src/themes/drum/assets/i18n/en.json5
In “src/assets/i18n/en.json5” overrode keys with values matching the following criteria by copying both the key and value to the “UMD Customization” section at the bottom of the file and modifying the value.
1) Replaced all instance of “DSpace” with “DRUM”.
2) Replaced all instances of “MyDSpace” with “My Submissions” and all instances of “Your submissions” to “My submissions” (capitalizing “submissions” as appropriate).
**Note:** The “MyDSpace” page (which was changed to “My Submissions”) had an existing page header of “Your submissions”. For consistency, modified the following entries:
* mydspace.results.head
* mydspace.show.workspace
* workspace.search.results.head
https://umd-dit.atlassian.net/browse/LIBDRUM-737
> LIBDRUM-737. Replace "DSpace" and "MyDSpace" branding

- README-DRUM.md
- src/assets/i18n/en.json5
- src/themes/drum/assets/i18n/en.json5
Moved all I18n customizations into the DSpace "global" I18n file at "src/assets/i18n/en.json5", placing them into a "UMD Customization" section at the bottom of the file.
This takes advantage of the behavior that when multiple instance of the same key are in the file, the "last" instance of the key is used.
Deleted the "theme" I18n file in "src/themes/drum/assets/i18n/en.json5" after verifying that all changes were present in the "UMD Customization" section of "src/assets/i18n/en.json5".
It was decided to modify the global "src/assets/i18n/en.json5" file directly, instead of using a "theme" file, which would require running the "merge-i18n" script whenever it was changed (which in turn would modify the "global" I18n file). It just seemed simpler to edit the "global" I18n file directly (in …
> LIBDRUM-760. Refactor I18n customizations into global "en.json5 file"

- README-DRUM.md
- src/assets/i18n/en.json5
- src/themes/drum/app/footer/footer.component.html
- src/themes/drum/app/footer/footer.component.scss
- src/themes/drum/assets/i18n/en.json5
Modified the “src/themes/drum/app/footer/footer.component.html” file,
keeping the “top” and “bottom” footer structure, but removing the
DSpace copyright and Lyrasis link.
Reordered the row of links in the bottom footer to
“Send Feedback | Privacy policy | Web Accessibility | Give Now | Cookie settings”
and removed the “text-white” class, so that the text color would match
the top footer.
Modified the “src/themes/drum/app/footer/footer.component.scss” file,
changing the “background-color” for the “footer” class
(the bottom footer) to use the same SCSS variable as the top footer,
so that the background colors would match.
Considered merging the “top” and “bottom” footer sections together to be
a single footer, but DSpace seems geared to have both sections, and the
CSS styling is different …
> LIBDRUM-745. Updated DRUM footer

- src/app/item-page/field-components/metadata-values/metadata-values.component.html
Modified the metadata field display on the "Item" page by removing the "preserve-line-breaks" CSS class, so that the multi-line "Abstract" and "Notes" fields are displayed as single blocks of text, ignoring any line breaks in the text. This is to make the display more similar to that of DSpace 6, which had the same behavior.
Without this change, the "Abstract" and "Notes" fields of many items displayed oddly, because the line breaks were not compatible with the available display width, leading to many short line fragments.
https://umd-dit.atlassian.net/browse/LIBDRUM-746
_Add references/links to any related issues or PRs. These may include:_
* Fixes #[issue-number]
* Requires DSpace/DSpace#[pr-number] (if a REST API PR is required to test this)
Short summary of changes (1-2 sentences). …
> LIBDRUM-746. Removed "preserve-line-breaks" on Item page metadata fields

- src/themes/drum/app/home-page/home-news/home-news.component.html
- src/themes/drum/app/home-page/home-news/home-news.component.scss
- src/themes/drum/app/home-page/home-news/home-news.component.ts
- src/themes/drum/app/navbar/navbar.component.scss
- src/themes/drum/eager-theme.module.ts
- src/themes/drum/styles/_theme_css_variable_overrides.scss
* Moved "HomeNewsComponent" into the "drum" theme
* Updated "hero image" text for DRUM
* Replaced background image
* Increased the font size of the text t in the “hero image” by 20%
* Changed the hyperlinks in the hero image text to “Maryland Gold” (#ffd200) from the the UMD palette (https://brand.umd.edu/colors )
* Change the bar between the navigation bar and the hero image to dark gray (#454545)
https://umd-dit.atlassian.net/browse/LIBDRUM-761
> LIBDRUM-761. Updated DRUM home page text and image

- src/app/home-page/recent-item-list/recent-item-list.component.html
- src/themes/drum/app/home-page/home-page.component.html
Modified the home page to show "List of Communities" and
"Recent Submissions" in a two-column layout.
The 2-column implementation required making changes to the stock
DSpace “recent-item-list” component, which is not themeable. Therefore,
the stock DSpace file
“src/app/home-page/recent-item-list/recent-item-list.component.html”
was customized in-place. The change in the file was adding Bootstrap
tags to suppress the margin top and dividing line in the “small” layouts
and above, so that the  “Recent Submissions” title in the second column
would line up with the “List of Communities” title  in the first column.
The “src/themes/drum/app/home-page/home-page.component.html” was also
modified to place the “List of Communities” and “Recent Submissions”
into a two-column layout, using Bootstrap …
> LIBDRUM-785. Change homepage to 2-column layout of communities/recent submissions

- src/themes/drum/assets/static-pages/health-ping.html
Simplest possible implementation of a "health-ping" page, using an HTML page stored as part of the assets.
The endpoint is "/assets/drum/static-pages/health-ping.html"
https://umd-dit.atlassian.net/browse/LIBDRUM-787
> LIBDRUM-787. Implementation of "health-ping" static HTML page

- .gitignore
- README-DRUM.md
- angular.json
Modified local development environment to use HTTPS, in order to restore CAS authentication.
In September 2023, DIT changed the CAS application firewall to reject with a "403 Forbidden" HTTP status code any CAS requests with a "service" HTTP parameter of "localhost" or "127.0.0.1".
This requires the local development environment to use a hostname other than "localhost" or "127.0.0.1", which in turn requires:
* Use the HTTPS protocol for all interactions with CAS
* Use a "full" hostname
* Use the "mkcert" application to register a certificate authority
* Have "drum-local.lib.umd.edu" and "api.drum.lib.umd.edu" hostnames added to the "/etc/hosts" file
* An Nginx container in the "docker-compose.yml" file for HTTPS handling
See the changes to "dspace/docs/CASAuthentication.md" for additional …
> LIBDRUM-815. Modify local development environment to use HTTPS

- config/config.yml
- docs/DrumAngularCustomization.md
- src/themes/drum/app/item-page/simple/item-types/untyped-item/untyped-item.component.html
Enabled Markdown rendering in the "Notes" (dc.description) field on the simple item page so that simple URLs would be rendered as clickable hyperlinks.
Added a "docs/DrumAngularCustomization.md" page to record DRUM-specific Angular customizations.
https://umd-dit.atlassian.net/browse/LIBDRUM-781
> LIBDRUM-781. Enable URL hyperlink rendering for the "Notes" field

- src/assets/i18n/en.json5
- src/themes/drum/app/item-page/simple/field-components/file-section/file-section.component.html
In the DSpace 7.6 upgrade, this file was modified to match the stock
DSpace file in which the "ngFor" iterator was part of the
"ds-themed-file-download-link" component, and the
"ds-bitstream-download-counter" component was part of the
"ds-themed-file-download-link" content. This caused an issue in which
the bitstream download count was included as part of the file hyperlink.
Fixed the issue by moving the "ngFor" iterator into a separate
"ngContainer", and moving the "ds-bitstream-download-counter" component
out of the content of the "ds-themed-file-download-link" component.
Also, moved the "No. of downloads:" text for the label used by the
"ds-bitstream-download-counter" component into the "en.json5" file.
This was done to maintain consistent use of I18n text. …
> LIBDRUM-827. Keep bitstream download count separate from file hyperlink

- src/app/core/data/base/base-data.service.spec.ts
- src/app/core/data/base/base-data.service.ts
- src/app/core/data/request-entry-state.model.spec.ts
- src/app/core/data/request-entry-state.model.ts
- src/app/core/data/request.reducer.spec.ts
- src/app/core/data/request.reducer.ts
- src/app/core/data/request.service.ts
- src/app/core/server-check/server-check.guard.spec.ts
- src/app/core/server-check/server-check.guard.ts
- src/app/core/shared/hal-endpoint.service.spec.ts
- src/app/core/shared/hal-endpoint.service.ts
The pull request incorporates the changes from the
dspace-angular upstream pull request 2670
(https://github.com/DSpace/dspace-angular/pull/2670)
The upstream pull request was merged into this codebase as follows:
1) In a web browser, went to the pull request URL (https://github.com/DSpace/dspace-angular/pull/2670), appended with “.patch”:
https://github.com/DSpace/dspace-angular/pull/2670.patch
This displayed an HTML page containing a Git emai-formatted patch file. Saved the file into the “dspace-angular” project directory as “2670.patch”.
2) Ran the following command in the “dspace-angular” project directory to apply the patch:
```
$ git am 2670.patch
```
The patch applied cleanly. No Shibboleth-specific files were modified in the patch, so the UMD CAS files did not need to be modified. …
> LIBDRUM-835. Fix "undefined doesn't contain the link authn" error when logging in

- src/themes/drum/app/header/header.component.html
- src/themes/drum/app/header/header.component.scss
- src/themes/drum/app/navbar/navbar.component.html
- src/themes/drum/app/navbar/navbar.component.scss
- src/themes/drum/styles/_theme_css_variable_overrides.scss
Incomplete merging of the DSpace 7.6.1 changes to the navigation bar HTML and SCSS was causing the DRUM logo to not appear in wider screens.
Migrated DSpace 7.6.1 changes in the "src/themes/dspace" theme into the "src/themes/drum" theme.
Also updated the "ds-header-navbar-border-bottom-color" SCSS variable in the "_theme_css_variable_overrides.scss" file to use the DRUM-preferred color.
https://umd-dit.atlassian.net/browse/LIBDRUM-842
> LIBDRUM-842. Restore DRUM logo to navigation bar

- docs/DrumAngularCustomization.md
- src/themes/drum/app/login-page/login-page.component.html
- src/themes/drum/app/login-page/login-page.component.scss
- src/themes/drum/app/login-page/login-page.component.ts
- src/themes/drum/lazy-theme.module.ts
- src/themes/drum/styles/_theme_css_variable_overrides.scss
Added the "login-page" component to the "drum" theme by copying the files from the "custom" theme. Modified the files to replace the DSpace logo on the /login page with the DRUM logo.
Added "--ds-login-logo-height/--ds-login-logo-width" to the "src/themes/drum/styles/_theme_css_variable_overrides.scss" file to set the correct width/height for the DRUM logo on the page.
Updated the "docs/DrumAngularCustomization.md" document.
https://umd-dit.atlassian.net/browse/LIBDRUM-843
> LIBDRUM-843. Replace DSpace logo on the /login page with DRUM logo

- docs/DrumAngularCustomization.md
- src/app/menu.resolver.ts
- src/assets/i18n/en.json5
Added a "Submit item to DRUM" menu entry to the navigation bar that displays for logged-in users that have "submit" permission to at least one collection.
This menu entry is essentially a duplicate of the "New | Item" menu entry in the administrative sidebar.
The "index" is set to "3" so that it will show at the end of the navigation bar entries (the index "2" is used by the "Statistics" menu entry).
https://umd-dit.atlassian.net/browse/LIBDRUM-839
> LIBDRUM-838. Added "Submit item to DRUM" menu entry to navigation bar

- src/themes/drum/app/community-list-page/community-list/community-list.component.html
- src/themes/drum/app/community-list-page/community-list/community-list.component.ts
In "community-list.component.ts", fixed the "Show More" button when displayed in subcommunities such as the
“MARAC Mid-Atlantic Regional Archives Conference” community by replacing the use of the "getMaxAllowedCommunities" method with the "nextPage" method. The "nextPage" method was modified to retrieve up to "MAX_COMCOLS_PER_PAGE" entries, instead of the DSpace default of 5 entries. The "getMaxAllowedCommunities" method was no longer needed, and so was removed
Replaced the use of "getMaxAllowedCommunities" in the "community-list.component.html" file with "getNextPage". This restores the HTML file to being identical with the stock DSpace version, but retaining the HTML file because this really represents the HTML for the UMD custom "ds-cg-community-list" component, not the stock DSpace …
> LIBDRUM-797. Fix "Show More" button for subcommunities

- src/assets/i18n/en.json5
- src/themes/drum/app/home-page/home-news/home-news.component.html
Implemented the following changes to the DRUM homepage based on a a February 6, 2024 email from Terry Owen:
1) In the banner, capitalize the "I" in Item so it reads
"Submit Item to DRUM".
2) In the last sentence of the text in the red box, capitalize the I in
the "Submit Item to DRUM" so the sentence would read:
> To submit an item to DRUM, login using your UMD credentials.
Then select the "Submit Item to DRUM" link in the navigation bar.
3) We need the last sentence to stand out, so please BOLD the last sentence:
**To submit an item to DRUM, login using your UMD credentials. Then select the "Submit Item to DRUM" link in the navigation bar.**
https://umd-dit.atlassian.net/browse/LIBDRUM-846
> LIBDRUM-846. Tweaks to DRUM homepage

- src/assets/i18n/en.json5
Added "Submission Type" label to apply to the "umdType" and "mhheaType" steps in the default and MHHEA submission forms.
https://umd-dit.atlassian.net/browse/LIBDRUM-876
> LIBDRUM-876. Added "Submission Type" label for "Type" form section

- src/app/admin/admin-sidebar/admin-sidebar-section/admin-sidebar-section.component.spec.ts
- src/app/admin/admin-sidebar/admin-sidebar-section/admin-sidebar-section.component.ts
- src/app/admin/admin-sidebar/admin-sidebar.component.spec.ts
- src/app/admin/admin-sidebar/admin-sidebar.component.ts
- src/app/admin/admin-sidebar/expandable-admin-sidebar-section/expandable-admin-sidebar-section.component.spec.ts
- src/app/home-page/recent-item-list/recent-item-list.component.html
- src/themes/drum/styles/_global-styles.scss
In LIBDRUM-872, the sidebar classes were modified to include a
"NativeWindowService" parameter in their constructors, so that the
browser and operating system could be determined. It was overlooked in
that issue that the unit tests also needed to be updated.
Modified the unit tests to include a mock NativeWindowService instance
as the "NativeWindowService" parameter provided to the class
constructors.
https://umd-dit.atlassian.net/browse/LIBDRUM-879
> LIBDRUM-879. Fixes to dspace-angular tests

- Dockerfile.prod
* Updated "Dockerfile.prod" to make it more closely match the stock "Dockerfile.dist" file, including using the stage Docker build.
* Fixed a "LegacyKeyValueFormat" warning that was being displayed when running the Docker build
* Capitialized “AS” to to fix a Docker build warning in line 5
https://umd-dit.atlassian.net/browse/LIBDRUM-874
> LIBDRUM-874. Updated "Dockerfile.prod" based on stock "Dockerfile.dist"

- src/themes/drum/app/header/header.component.html
- src/themes/dspace/app/header-nav-wrapper/header-navbar-wrapper.component.scss
- src/themes/dspace/app/navbar/navbar.component.html
Incorporates the changes from dspace-angular Pull Request
3513, into the appropriate "drum" and "dspace" theme files.
The changes in Pull Request 3513 enable the entries in the navigation
bar to perform text wrapping at smaller browser widths (similar to the
behavior in DSpace 7.6.1) so that the right-most navigation bar entries
are available at nearly all browser widths.
There are still some browser widths at which the right-most entry is
fully obscured, but this same behavior was also seen in DSpace 7.6.1.
https://umd-dit.atlassian.net/browse/LIBDRUM-873
> LIBDRUM-873. Enable text wrapping in navigation bar entries

- src/app/profile-page/profile-page.component.html
- src/app/profile-page/profile-page.component.spec.ts
- src/app/profile-page/profile-page.component.ts
This code change to suppress the "Researcher Profile" panel on the "Update Profile" page is taken from commit "ded0079" of dspace-angular pull request 3585.
Customization markers have been added to indicate that the changes came from a stock DSpace pull request, and can be removed when DRUM is upgraded to a version incorporating the changes.
https://umd-dit.atlassian.net/browse/LIBDRUM-890
> LIBDRUM-890. Suppress "Researcher Profile" panel on "Update Profile"

- src/app/access-control/unit-registry/unit-form/unit-form.component.ts
- src/app/access-control/unit-registry/units-registry.component.ts
- src/app/etdunit-registry/etdunits-registry.component.ts
Updated the following components to use the DSONameService when displaying the name of the component instance, following the examples in the stock DSpace classes:
* src/app/access-control/unit-registry/units-registry.component.ts
* src/app/access-control/unit-registry/unit-form/unit-form.component.ts
* src/app/etdunit-registry/etdunits-registry.component.ts
https://umd-dit.atlassian.net/browse/LIBDRUM-899
> LIBDRUM-899. Updated UMD components to use DSONameService

- src/app/core/provide-core.ts
Incorporated the changes in DSpace Pull Request 3671 to fix the display of the System-wide Alert banner.
The "UMD Customization" markers added in this commit can be removed once DRUM is upgraded to a DSpace version incorporating the change.
https://umd-dit.atlassian.net/browse/LIBDRUM-904
> LIBDRUM-904. Fix display of System-wide Alert banner

- config/config.example.yml
- server.ts
- src/app/app.config.ts
- src/app/core/dspace-rest/dspace-rest.interceptor.spec.ts
- src/app/core/dspace-rest/dspace-rest.interceptor.ts
- src/app/core/services/server-hard-redirect.service.spec.ts
- src/app/core/services/server-hard-redirect.service.ts
- src/app/shared/utils/safe-url-pipe.ts
- src/app/thumbnail/thumbnail.component.html
- src/app/thumbnail/thumbnail.component.spec.ts
- src/app/thumbnail/thumbnail.component.ts
- src/config/config.server.ts
- src/config/server-config.interface.ts
- src/config/ssr-config.interface.ts
- src/environments/environment.production.ts
- src/environments/environment.test.ts
- src/environments/environment.ts
- src/modules/app/browser-init.service.ts
- src/modules/app/server-init.service.ts
Back-port of "ssrBaseUrl" functionality from
DSpace-angular pull request 3953.
Implements the ability for Angular Universal to
communicate directly with the DRUM back-end
pod, instead of going through the ingress.
This change was needed for the AWS migration.
https://umd-dit.atlassian.net/browse/LIBDRUM-943
> LIBDRUM-943. Back-port of DSpace 7.6.3 "ssrBaseUrl" functionality
